# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 16:53
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='/docs')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(b'SuperUser', b'SuperUser'), (b'Requester', b'Requester'), (b'Approver', b'Approver'), (b'Purchaser', b'Purchaser'), (b'Receiver', b'Receiver'), (b'Payer', b'Payer')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(blank=True, max_length=150, null=True)),
                ('sku', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_type', models.CharField(default='each', max_length=20)),
                ('currency', models.CharField(choices=[(b'USD', b'USD'), (b'INR', b'INR')], default='USD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('currency', models.CharField(blank=True, choices=[(b'USD', b'USD'), (b'INR', b'INR')], max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, default='../static/img/default_logo.jpg', null=True, upload_to='logos')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_issued', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date_due', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(choices=[(b'USD', b'USD'), (b'INR', b'INR')], default='USD', max_length=10)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(b'Billing', b'Billing'), (b'Shipping', b'Shipping'), (b'HQ', b'HQ')], default='Billing', max_length=20)),
                ('address1', models.CharField(blank=True, max_length=40, null=True)),
                ('address2', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, choices=[(b'India', b'India'), (b'USA', b'USA')], max_length=20, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comments', models.CharField(blank=True, max_length=150, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_due', models.DateField(default=django.utils.timezone.now)),
                ('account_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.AccountCode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.CatalogItem')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 'Awful'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Great')])),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied'), ('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid'), ('Archived', 'Archived')], default='Draft', max_length=10)),
                ('color', models.CharField(choices=[('Pending', 'yellow'), ('Approved', 'green'), ('Denied', 'red'), ('Other', 'grey')], default='Other', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='eProc.BuyerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerCo',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eProc.Company')),
            ],
            bases=('eProc.company',),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eProc.Document')),
                ('cost_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('terms', models.CharField(blank=True, max_length=5000, null=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('eProc.document', models.Model),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eProc.Document')),
                ('cost_shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('terms', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('eProc.document', models.Model),
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eProc.Document')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions', to='eProc.Department')),
            ],
            bases=('eProc.document',),
        ),
        migrations.CreateModel(
            name='VendorCo',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eProc.Company')),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_details', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_number', models.BigIntegerField(blank=True, null=True)),
                ('company_number', models.CharField(blank=True, max_length=20, null=True)),
                ('buyer_co', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_cos', to='eProc.BuyerCo')),
            ],
            bases=('eProc.company',),
        ),
        migrations.AddField(
            model_name='status',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='eProc.Document'),
        ),
        migrations.AddField(
            model_name='rating',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='eProc.Company'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.Tax'),
        ),
        migrations.AddField(
            model_name='location',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='eProc.Company'),
        ),
        migrations.AddField(
            model_name='document',
            name='next_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_to_approve', to='eProc.BuyerProfile'),
        ),
        migrations.AddField(
            model_name='document',
            name='preparer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_prepared_by', to='eProc.BuyerProfile'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='eProc.Category'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='eProc.Department'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='eProc.VendorCo'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='billing_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_billed', to='eProc.Location'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_shipped', to='eProc.Location'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendorCo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_orders', to='eProc.VendorCo'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.Requisition'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_billed', to='eProc.Location'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='eProc.PurchaseOrder'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_add',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_shipped', to='eProc.Location'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendorCo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_orders', to='eProc.VendorCo'),
        ),
        migrations.AddField(
            model_name='document',
            name='buyerCo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='eProc.BuyerCo'),
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='eProc.BuyerCo'),
        ),
        migrations.AddField(
            model_name='category',
            name='buyerCo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='eProc.BuyerCo'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='buyerCo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='eProc.BuyerCo'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='vendorCo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='eProc.VendorCo'),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='eProc.BuyerCo'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='eProc.VendorCo'),
        ),
        migrations.AddField(
            model_name='accountcode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_codes', to='eProc.BuyerCo'),
        ),
    ]
