# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='fax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorco',
            name='comments',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendorco',
            name='contact_rep',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendorco',
            name='vendorID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
