# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import eProc.models
import eProc.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=eProc.models.img_directory_path, validators=[eProc.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_approved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_ordered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty_delivered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty_ordered',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty_returned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
