# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('Billing', 'Billing'), ('Shipping', 'Shipping'), ('HQ', 'HQ')], default='HQ', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('INR', 'INR')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address1',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='HQ/Primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
