# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='buyerCo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='eProc.BuyerCo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountcode',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
