# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0002_auto_20161102_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorco',
            name='buyer_cos',
        ),
        migrations.AddField(
            model_name='vendorco',
            name='buyer_co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_cos', to='eProc.BuyerCo'),
        ),
    ]
