# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0002_auto_20161123_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='loc_type',
        ),
    ]
