# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0002_auto_20170128_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Ordered', b'Ordered'), (b'Cancelled', b'Cancelled'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Returned', b'Returned'), (b'Paid', b'Paid'), (b'Drawdown Partial', b'Drawdown Partial'), (b'Drawdown Complete', b'Drawdown Complete'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='drawdownitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Ordered', b'Ordered'), (b'Cancelled', b'Cancelled'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Returned', b'Returned'), (b'Paid', b'Paid'), (b'Drawdown Partial', b'Drawdown Partial'), (b'Drawdown Complete', b'Drawdown Complete'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_billed', to='eProc.Location'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_shipped', to='eProc.Location'),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Ordered', b'Ordered'), (b'Cancelled', b'Cancelled'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Returned', b'Returned'), (b'Paid', b'Paid'), (b'Drawdown Partial', b'Drawdown Partial'), (b'Drawdown Complete', b'Drawdown Complete'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='billing_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_billed', to='eProc.Location'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_add',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder_shipped', to='eProc.Location'),
        ),
    ]
