# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0002_auto_20170223_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Ordered Partial', b'Ordered Partial'), (b'Ordered Complete', b'Ordered Complete'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Returned', b'Returned'), (b'Drawndown Partial', b'Drawndown Partial'), (b'Drawndown Complete', b'Drawndown Complete')], default='Pending', max_length=25),
        ),
    ]
