# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0002_auto_20161122_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='type',
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, choices=[(b'India', b'India'), (b'USA', b'USA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='HQ', max_length=20),
        ),
    ]
