# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 19:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0003_item_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='sub_total',
        ),
        migrations.AlterField(
            model_name='drawdownitem',
            name='qty_drawndown',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='invoices', to='eProc.PurchaseOrder'),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Ordered Partial', b'Ordered Partial'), (b'Ordered Complete', b'Ordered Complete'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Returned Complete', b'Returned Complete'), (b'Drawndown', b'Drawndown')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty_approved',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty_cancelled',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty_denied',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='qty_requested',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty_delivered',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty_ordered',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty_returned',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
