# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0003_auto_20161122_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='typee',
            field=models.CharField(choices=[(b'Billing', b'Billing'), (b'Shipping', b'Shipping'), (b'HQ', b'HQ')], default='Billing', max_length=15),
        ),
    ]
