# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0003_auto_20161123_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='buyerCo',
            new_name='buyer_co',
        ),
        migrations.RenameField(
            model_name='catalogitem',
            old_name='vendorCo',
            new_name='vendor_co',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='buyerCo',
            new_name='buyer_co',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='buyerCo',
            new_name='buyer_co',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='vendorCo',
            new_name='vendor_co',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='vendorCo',
            new_name='vendor_co',
        ),
        migrations.RemoveField(
            model_name='location',
            name='company',
        ),
        migrations.AddField(
            model_name='location',
            name='buyer_co',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='eProc.BuyerCo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='vendor_co',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='eProc.VendorCo'),
            preserve_default=False,
        ),
    ]
