# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0003_auto_20170204_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='purchase_order',
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_orders',
            field=models.ManyToManyField(related_name='invoices', to='eProc.PurchaseOrder'),
        ),
    ]
