# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0004_auto_20161123_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='buyer_co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='eProc.BuyerCo'),
        ),
        migrations.AlterField(
            model_name='location',
            name='vendor_co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='eProc.VendorCo'),
        ),
    ]
