# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0004_auto_20170204_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_issued',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_issued',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
