# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0005_auto_20170225_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spend', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_allocation', to='eProc.AccountCode')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_allocation', to='eProc.Department')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_by_dept', to='eProc.OrderItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='spendbreakdown',
            name='account_code',
        ),
        migrations.RemoveField(
            model_name='spendbreakdown',
            name='department',
        ),
        migrations.RemoveField(
            model_name='spendbreakdown',
            name='item',
        ),
        migrations.DeleteModel(
            name='SpendBreakdown',
        ),
    ]
