# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0005_auto_20161104_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcode',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_codes', to='eProc.BuyerCo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='comments',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
