# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170225_2228'),
        ('eProc', '0007_document_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=32)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='home.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='buyerco',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
