# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0007_auto_20170206_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='buyer_co',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='eProc.BuyerCo'),
        ),
    ]
