# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0007_auto_20161104_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(default='USD', max_length=30),
        ),
    ]
