# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0008_category_buyer_co'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='buyer_co',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='buyer_co',
            field=models.ManyToManyField(blank=True, null=True, related_name='catalog_items', to='eProc.BuyerCo'),
        ),
        migrations.RemoveField(
            model_name='vendorco',
            name='buyer_co',
        ),
        migrations.AddField(
            model_name='vendorco',
            name='buyer_co',
            field=models.ManyToManyField(blank=True, null=True, related_name='vendor_cos', to='eProc.BuyerCo'),
        ),
    ]
