# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0009_buyerco_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerco',
            name='created_at',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
