# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0009_orderitem_date_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
