# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0009_auto_20170206_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='description',
        ),
    ]
