# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0010_remove_catalogitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='buyer_co',
            new_name='buyer_cos',
        ),
    ]
