# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0011_auto_20170207_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eProc.Department'),
            preserve_default=False,
        ),
    ]
