# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0011_auto_20161110_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.TextField(choices=[('grey', 'grey'), ('yellow', 'yellow'), ('green', 'green'), ('red', 'red')], default='grey'),
        ),
    ]
