# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0011_auto_20170227_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitemrequest',
            name='max_price',
        ),
        migrations.AddField(
            model_name='catalogitemrequest',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='catalogitemrequests', to='eProc.BuyerProfile'),
            preserve_default=False,
        ),
    ]
