# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0011_auto_20161123_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcode',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='accountcode',
            name='departments',
            field=models.ManyToManyField(related_name='account_codes', to='eProc.Department'),
        ),
        migrations.AddField(
            model_name='accountcode',
            name='expense_type',
            field=models.CharField(choices=[(b'Asset', b'Asset'), (b'Expense', b'Expense')], default='Expense', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
