# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-12 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import eProc.models
import eProc.validators


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0012_orderitem_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='department',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='departments',
            field=models.ManyToManyField(related_name='items', to='eProc.Department'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=eProc.models.file_directory_path, validators=[eProc.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
