# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-28 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0012_auto_20170227_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(choices=[(b'Steel', b'Steel'), (b'Cement', b'Cement')], max_length=100)),
                ('currency', models.CharField(blank=True, choices=[(b'USD', b'USD'), (b'INR', b'INR')], max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='eProc.BuyerProfile')),
                ('buyer_co', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='eProc.BuyerCo')),
            ],
        ),
    ]
