# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 04:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0013_auto_20170212_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Success', 'Success'), ('Info', 'Info'), ('Warning', 'Warning'), ('Error', 'Error')], default='Info', max_length=20)),
                ('is_unread', models.BooleanField(default=True)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient', models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='tax',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eProc.Department'),
            preserve_default=False,
        ),
    ]
