# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0014_auto_20170213_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='recipients',
        ),
    ]
