# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import eProc.models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0014_remove_status_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=eProc.models.file_directory_path)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='eProc.Document')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../static/img/default_profile_pic.jpg', null=True, upload_to=eProc.models.user_img_directory_path),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='../static/img/default_logo.jpg', null=True, upload_to=eProc.models.co_logo_directory_path),
        ),
    ]
