# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0015_auto_20170213_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='grand_total',
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('Info', 'Info'), ('Success', 'Success'), ('Warning', 'Warning'), ('Error', 'Error')], default='Info', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(blank=True, null=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
