# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-10 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0015_auto_20170228_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='threshold',
            new_name='min_threshold',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='max_threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
