# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0015_auto_20161128_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_paid',
        ),
    ]
