# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0016_remove_invoice_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='company',
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='eProc.Document'),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
