# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0016_auto_20170310_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='tax',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='eProc.BuyerCo'),
            preserve_default=False,
        ),
    ]
