# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0017_auto_20161128_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[(b'Requested', b'Requested'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Draft', b'Draft'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Archived', b'Archived')], default='Draft', max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentstatus_updates', to='eProc.BuyerProfile')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='eProc.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItemStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[(b'Requested', b'Requested'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Draft', b'Draft'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Archived', b'Archived')], default='Draft', max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitemstatus_updates', to='eProc.BuyerProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='status',
            name='author',
        ),
        migrations.RemoveField(
            model_name='status',
            name='document',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='orderitemstatus',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='eProc.OrderItem'),
        ),
    ]
