# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0018_debitnote_debitnoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnoteitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debitnoteitem',
            name='desc',
            field=models.CharField(default='xxx', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debitnoteitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
