# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0018_auto_20161128_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentstatus',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterModelOptions(
            name='orderitemstatus',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='file',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
