# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0019_auto_20161130_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='terms',
        ),
        migrations.AddField(
            model_name='document',
            name='terms',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Requested', b'Requested'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Draft', b'Draft'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Archived', b'Archived')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Requested', b'Requested'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Draft', b'Draft'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Archived', b'Archived')], default='Pending', max_length=15),
        ),
    ]
