# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0020_auto_20161202_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.Invoice'),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Requested', b'Requested'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Archived', b'Archived')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Requested', b'Requested'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Archived', b'Archived')], default='Pending', max_length=15),
        ),
    ]
