# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0021_auto_20161202_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawdown',
            fields=[
                ('document_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='eProc.Document')),
            ],
            bases=('eProc.document',),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Paid', b'Paid'), (b'Drawndown', b'Drawndown'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Archived', b'Archived')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Paid', b'Paid'), (b'Drawndown', b'Drawndown'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Archived', b'Archived')], default='Pending', max_length=15),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='drawdown',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.Drawdown'),
        ),
    ]
