# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0022_auto_20161206_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Paid', b'Paid'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawndown', b'Drawndown'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Completed', b'Completed'), (b'Archived', b'Archived')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='account_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.AccountCode'),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Paid', b'Paid'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawndown', b'Drawndown'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Completed', b'Completed'), (b'Archived', b'Archived')], default='Pending', max_length=15),
        ),
    ]
