# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0023_auto_20161206_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='eProc.Requisition'),
        ),
    ]
