# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0024_auto_20161206_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Paid', b'Paid'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawndown', b'Drawndown'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Completed', b'Completed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Delivered', b'Delivered'), (b'Paid', b'Paid'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawndown', b'Drawndown'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Open', b'Open'), (b'Closed', b'Closed'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Cancelled', b'Cancelled'), (b'Paid', b'Paid'), (b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Completed', b'Completed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
    ]
