# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0025_auto_20161206_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qty_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='qty_delivered',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='qty_ordered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Delivered', b'Delivered'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawdown Cancelled', b'Drawdown Cancelled'), (b'Drawdown Completed', b'Drawdown Completed'), (b'Pending', b'Pending'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Open', b'Open'), (b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Delivered', b'Delivered'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawdown Cancelled', b'Drawdown Cancelled'), (b'Drawdown Completed', b'Drawdown Completed'), (b'Pending', b'Pending'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
    ]
