# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0026_auto_20161208_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qty_returned',
            field=models.IntegerField(default=0),
        ),
    ]
