# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0027_orderitem_qty_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='comments_delivery',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comments_order',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawdown Cancelled', b'Drawdown Cancelled'), (b'Drawdown Partial', b'Drawdown Partial'), (b'Drawdown Complete', b'Drawdown Complete'), (b'Pending', b'Pending'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Requested', b'Requested'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawdown Cancelled', b'Drawdown Cancelled'), (b'Drawdown Partial', b'Drawdown Partial'), (b'Drawdown Complete', b'Drawdown Complete'), (b'Pending', b'Pending'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
    ]
