# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0028_auto_20161211_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
