# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0029_catalogitem_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='location',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='eProc.Location'),
            preserve_default=False,
        ),
    ]
