# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0031_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='relates_to',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='eProc.BuyerProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='role',
            field=models.CharField(choices=[(b'SuperUser', b'SuperUser'), (b'Requester', b'Requester'), (b'Approver', b'Approver'), (b'Purchaser', b'Purchaser'), (b'Receiver', b'Receiver'), (b'Payer', b'Payer'), (b'Inventory Manager', b'Inventory Manager')], max_length=15),
        ),
        migrations.AlterField(
            model_name='documentstatus',
            name='value',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawdown Cancelled', b'Drawdown Cancelled'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitemstatus',
            name='value',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Approved', b'Approved'), (b'Ordered', b'Ordered'), (b'Denied', b'Denied'), (b'Cancelled', b'Cancelled'), (b'Delivered Partial', b'Delivered Partial'), (b'Delivered Complete', b'Delivered Complete'), (b'Drawdown Requested', b'Drawdown Requested'), (b'Drawdown Approved', b'Drawdown Approved'), (b'Drawdown Denied', b'Drawdown Denied'), (b'Drawdown Cancelled', b'Drawdown Cancelled'), (b'Closed', b'Closed'), (b'Archived', b'Archived')], default='Pending', max_length=20),
        ),
    ]
