# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0032_auto_20161218_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[(b'Real Estate', b'Real Estate'), (b'Manufacturing', b'Manufacturing'), (b'Hospitals', b'Hospitals')], max_length=20, null=True),
        ),
    ]
