# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0033_company_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='vendor_co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='eProc.VendorCo'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_co',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to='eProc.VendorCo'),
        ),
    ]
