# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-24 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0034_auto_20161220_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='score',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='company',
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='eProc.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='ratee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to='eProc.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='eProc.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
