# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0035_auto_20161224_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='relates_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eProc.BuyerProfile'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
