# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0037_auto_20170108_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerprofile',
            name='relates_to',
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
