# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0038_auto_20170108_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='approval_threshold',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='VendorProfile',
        ),
    ]
