# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0039_auto_20170111_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.AddField(
            model_name='department',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='role',
            field=models.CharField(choices=[(b'SuperUser', b'SuperUser'), (b'Requester', b'Requester'), (b'Approver', b'Approver'), (b'Purchaser', b'Purchaser'), (b'Receiver', b'Receiver'), (b'Inventory Manager', b'Inventory Manager'), (b'Payer', b'Payer')], max_length=15),
        ),
    ]
