# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProc', '0041_auto_20170120_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='comments',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comments_drawdown',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comments_request',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='comments_delivery',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='comments_order',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
