# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price_per_user', models.IntegerField(default=10)),
            ],
        ),
    ]
