# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-23 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='xx', max_length=40),
            preserve_default=False,
        ),
    ]
