# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161118_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('Demo', 'I want to book a demo'), ('Pricing', 'I have a question about pricing'), ('Billing', 'I have a question about billing'), ('Partnerships', 'I want to talk about partnerships'), ('Other', 'Other')], max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
