# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='source',
            field=models.CharField(default='blog author', max_length=40),
            preserve_default=False,
        ),
    ]
