# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_author_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='source',
            field=models.CharField(choices=[('Blog Author', 'Blog Author'), ('Contact Form', 'Contact Form'), ('Newsletter', 'Newsletter')], max_length=40),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
