# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170223_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price_per_user',
            new_name='price_per_month',
        ),
        migrations.AddField(
            model_name='plan',
            name='analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='bulk_purchasing',
            field=models.BooleanField(default=False),
        ),
    ]
