# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170225_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
