# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170225_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(choices=[(b'USD', b'USD'), (b'INR', b'INR')], default='USD', max_length=5),
        ),
        migrations.AlterField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('month', 'month'), ('year', 'year')], default='month', max_length=20),
        ),
    ]
